DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS HOLIDAYS;

CREATE TABLE USERS (
  ID       BIGINT       NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(12)  NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  ROLE     VARCHAR(16)  NOT NULL,
  UNIQUE UQ_USER_1 (USERNAME),
  PRIMARY KEY (ID)
);

CREATE TABLE HOLIDAYS (
  ID    BIGINT      NOT NULL AUTO_INCREMENT,
  NAME  VARCHAR(30) NOT NULL,
  DAY   INT         NOT NULL,
  MONTH INT         NOT NULL,
  UNIQUE UQ_HOLIDAY_1 (NAME),
  PRIMARY KEY (ID)
);