INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES ('admin', '$2a$11$3D2Upsiw7w2mPJ3WDEaPMOC.3eCVZ0Nirs8CxOlH/G15yxW9qNnNG', 'ROLE_ADMIN');

INSERT INTO HOLIDAYS (NAME, DAY, MONTH) VALUES ('Independence day', 24, 7);
INSERT INTO HOLIDAYS (NAME, DAY, MONTH) VALUES ('New Year', 1, 0);
INSERT INTO HOLIDAYS (NAME, DAY, MONTH) VALUES ('Christmas', 7, 0);